### ISSUE TITLE
#2 Task

### ISSUE THREAD

**Issue by krasnotsvetov** [ww898/summer_student_practice_jb_2017_tests#1]
Здравствуйте,

Корректен ли файл GameOfLife.bsjb в 2-ой задаче в тестах? 
Например, при парсинге таблицы 0x0A я натыкаюсь на некорректный CodedIndex в 0-ой строке.
Более того, даже таблица Module 0x00 содержит не корректные(т.е в тех местах, где следует быть нулям, находятся не нули) данные.

Кроме того, хотел бы уточнить, какой формат вы считаете читаемым для ответа? Хотите ли вы увидеть подстановку вместо индексов в кучи #string и #guid, #blob самих строк в выводе таблицы?

Достаточно ли такого вывода?:)  (пример части данных)
[Async.pdb.GUID.txt](https://github.com/ww898/summer_student_practice_jb_2017_tests/files/983331/Async.pdb.GUID.txt)
[Async.pdb.Tables.txt](https://github.com/ww898/summer_student_practice_jb_2017_tests/files/983330/Async.pdb.Tables.txt)

**Comment by ww898** [comment]
Здравствуйте,

Файл `GameOfLife.bsjb` содержит ~корректные~ реальные метаданные программы (исходный PE-файл [тут](https://github.com/ww898/summer_student_practice_jb_2017_tests/blob/master/test_data/pe/GameOfLife.exe) ). В тестовом наборе есть файлы с неточным следованием стандартам - увы реальная жизнь немного отличается от описания. Сейчас я все проверю еще раз.

Могу вам предложить использовать [CFF Explorer](http://www.ntcore.com/exsuite.php) (только PE-файлы) или [dotPeek](https://www.jetbrains.com/decompiler/) для ручной проверки работоспособности вашей программы.

Мне бы хотелось, чтобы результат работы был такой: один исходный файл и один результирующий. В результирующем файле мне бы хотелось увидеть (порядок вывода не важен, строгих указаний нет):
1. Расшифрованный заголовок метаданных
2. Название (если есть), размер и количество элементов для каждой таблицы. Например так:
```
00 <имя таблицы> <размер элемента таблицы> <количество элементов в таблице>
01 <имя таблицы> <размер элемента таблицы> <количество элементов в таблице>
...
3F <имя таблицы> <размер элемента таблицы> <количество элементов в таблице>
```
3. Описание полей с размером, смещением и типом для каждой таблицы и значения в 16-тиричном виде с расшифровкой для `#Strings` и `#GUID`.  Например так:
```
<размер элемента таблицы> <количество элементов в таблице> <имя таблицы>

<смещение поля в элементе> <размер поля> <тип поля> <имя поля>
<смещение поля в элементе> <размер поля> <тип поля> <имя поля>
...
<смещение поля в элементе> <размер поля> <тип> <имя поля>

 0  <hex значение поля> <hex значение поля> ... <hex значение поля> <строка или GUID> <строка или GUID> ... <строка или GUID>
 1  <hex значение поля> <hex значение поля> ... <hex значение поля> <строка или GUID> <строка или GUID> ... <строка или GUID>
...
K-1 <hex значение поля> <hex значение поля> ... <hex значение поля> <строка или GUID> <строка или GUID> ... <строка или GUID>
```

**Comment by krasnotsvetov** [comment]
Спасибо за пояснение, возникли ещё два вопроса:

1. Посмотрел через CFF Explorer на данный файл, результаты такие же как у меня, не могли бы подсказать тогда, а что это значит в реальной жизни? Почему получается так?  (Например самоприменил к своей программе, тоже некоторые таблицы содержат кривые CodedIndex-ы)
В случае с GameOfLife.exe  таблица 0x0A "MemberRef"  в 0-ой строке в 1-ой колонке содержит 
CodedIndex от MemberRefParent, где всего 5 элементов(индексы от 0 до 4), но разобранное значение ссылается на 6-ую таблицу (вернее 6-ой индекс) из этих 5. Что значит такая ситуация? (в спецификациях я что-то ничего не вижу об этом)

      Спрашиваю к тому, что непонятно что в output тогда писать.

2. Элемент таблицы == строка(row)?

**Comment by ww898** [comment]
Вы молодец, что обратили внимание на несовпадение. Вы наткнулись на неофициальное расширение для CoreCLR - бит `CMiniMdSchemaBase::EXTRA_DATA`:

Полное описание структуры на С++:
```cpp
#pragma pack(push, 1)
struct CMiniMdSchemaBase
{
    ULONG m_ulReserved; // Reserved, must be zero.
    BYTE m_major;       // Version numbers.
    BYTE m_minor;
    BYTE m_heaps;       // Bits for heap sizes.
    BYTE m_rid;         // log-base-2 of largest rid.

    // Bits for heap sizes.
    enum
    {
        HEAP_STRING_4 = 0x01,
        HEAP_GUID_4   = 0x02,
        HEAP_BLOB_4   = 0x04,

        PADDING_BIT   = 0x08,       // Tables can be created with an extra bit in columns, for growth.

        DELTA_ONLY    = 0x20,       // If set, only deltas were persisted.
        EXTRA_DATA    = 0x40,       // If set, schema persists an extra 4 bytes of data.
        HAS_DELETE    = 0x80,       // If set, this metadata can contain _Delete tokens.
    };

    UINT64 m_maskvalid; // Bit mask of present table counts.
    UINT64 m_sorted;   // Bit mask of sorted tables.
};
#pragma pack(pop)
```

Я должен это отметить в задании - моё упущение...

2. Ну да - строка, в принципе у вас все было сделано правильно в выходном файле `Async.pdb.Tables.txt`, но немного сумбурно и не очень системно.

**Comment by krasnotsvetov** [comment]
1. По поводу output-а, я уже переделываю, как Вы сказали, и как раз в CFF примерно так же, да... более удобный формат. 

2. Теперь понятно почему там 64 было (heapSizes), теперь всё отлично.  Спасибо!

3. В некоторых местах вместо #~ встречается #- стрим  Log4net.dll(bsjb).  С ним надо разбираться?
В нем как раз тоже оказывается бывают дополнительные флаги в HeapSizes как DELTA_ONLY, EXTRA_DATA  и HAS_DELETE.

**Comment by ww898** [comment]
По последнему пункту: `#~` в общем эквивалентно `#-`. `HAS_DELETE` и `DELTA_ONLY` можно не учитывать, он нужны только для индикации инкрементальной записи метаданных, на сам формат они не влияют никак. `PADDING_BIT` сейчас не используется.

**Comment by ww898** [comment]
Задание поправил

**Comment by krasnotsvetov** [comment]
> По последнему пункту: #~ в общем эквивалентно #-. HAS_DELETE и DELTA_ONLY можно не учитывать, он нужны только для индикации инкрементальной записи метаданных, на сам формат они не влияют никак. PADDING_BIT сейчас не используется.

Структурную изоморфность без этих битов заметил, волновали только они:)

Спасибо за пояснение! :)

P.S наверное можно закрыть теперь
